@startuml シーケンス図
title シーケンス図(受講生)

actor 受講生
受講生 -> アカウント管理システム: ユーザ登録
アカウント管理システム -> 受講生: ユーザ登録完了

受講生 -> 講座管理システム: コンテンツを閲覧
講座管理システム -> 受講生: コンテンツ一覧を表示

受講生 -> 講座管理システム: コンテンツを選択
講座管理システム -> 受講生: コンテンツ詳細を表示

受講生 -> 講座管理システム: カートに追加
受講生 -> 講座管理システム: クーポンを照会
受講生 -> 請求管理システム: クーポンを適用
受講生 -> 請求管理システム: 購入を確定
請求管理システム -> アカウント管理システム: クレジット情報を照会
請求管理システム --> 講座管理システム: 支払い完了通知
講座管理システム -> 受講生: 購入完了通知

@enduml
