#!/bin/sh
## prepare-commit-msg

readonly COMMIT_MSG_FILE=$1
readonly COMMIT_SOURCE=$2

case "${COMMIT_SOURCE}" in
    commit) # use -c/-C/--amend
        : # 何もしない
    ;;
    *)
        # ブランチ名取得
        branch_name=$(git name-rev --name-only HEAD)
        # テンプレートファイルの [branchname] をブランチ名に置換
        sed -i.bak "s/\[branchname\]/${branch_name}/g" $COMMIT_MSG_FILE
    ;;
esac